version: '3.5'

services:
  backend:
    # You can build your own image from the source running:
    # $ make build
    # $ make tag_latest
    image: "moodlenet/moodlenet:latest"
    ports:
      - "4000:4000" # you may want to comment this in production
      - "80:80"
      - "443:443"
    env_file:
      - config/docker.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./uploads
        target: /var/www/uploads
  db:
    image: postgres:9.6-alpine
    # volumes:
    #   - "./volumes/postgres:/var/lib/postgresql/data"
    # ports:
    #   - "5432:5432"
    env_file:
      - config/docker.env
